import { Entity } from '../../../../types';

export const throwErrorIfNotUniqueOnAnything = ({ entity }: { entity: Entity }) => {
  if (entity.unique.length === 0) {
    throw new Error(
      `Entity '${entity.name}' must be unique on atleast one property. If it is not unique on any natural keys, you can make it unique on the autogenerated 'uuid' property instead.`,
    );
  }
};
