import { Entity } from '../../../../domain';

const reservedPropertyNames = ['id', 'uuid', 'created_at', 'updated_at', 'effective_at']; // we do not allow overwriting these autogenerated values.
export const throwErrorIfAnyReservedPropertyNamesAreUsed = ({ entity }: { entity: Entity }) => {
  const usedPropertyNames = Object.keys(entity.properties);
  usedPropertyNames.forEach((name) => {
    if (reservedPropertyNames.includes(name)) {
      throw new Error(
        `property can not be named "${entity.name}.${name}" because "${name}" is a reserved property name`,
      );
    }
  });
};
